"""initial schema

Revision ID: edd85523cefa
Revises: 
Create Date: 2026-08-12 13:08:29.045375
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'edd85523cefa'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default='EDITOR', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('VIEWER', 'EDITOR', 'APPROVER')", name=op.f('ck_app_user_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('login_id', name=op.f('uq_app_user_login_id'))
    )
    op.create_table('client',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client')),
    sa.UniqueConstraint('name', name=op.f('uq_client_name'))
    )
    op.create_index(op.f('ix_client_normalized_name'), 'client', ['normalized_name'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('contact_name', sa.Text(), nullable=True),
    sa.Column('honorific', sa.Text(), server_default='御中', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer')),
    sa.UniqueConstraint('code', name=op.f('uq_customer_code'))
    )
    op.create_table('item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tax_category', sa.Text(), server_default='STANDARD', nullable=False),
    sa.Column('billing_group', sa.Text(), server_default='EQUIPMENT', nullable=False),
    sa.Column('is_billable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("billing_group IN ('EQUIPMENT', 'COUNTER')", name=op.f('ck_item_billing_group')),
    sa.CheckConstraint("tax_category IN ('STANDARD', 'REDUCED')", name=op.f('ck_item_tax_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item')),
    sa.UniqueConstraint('code', name=op.f('uq_item_code'))
    )
    op.create_index(op.f('ix_item_billing_group'), 'item', ['billing_group'], unique=False)
    op.create_index(op.f('ix_item_tax_category'), 'item', ['tax_category'], unique=False)
    op.create_table('office',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_office')),
    sa.UniqueConstraint('code', name=op.f('uq_office_code'))
    )
    op.create_table('sales_rep',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_rep')),
    sa.UniqueConstraint('code', name=op.f('uq_sales_rep_code'))
    )
    op.create_table('billing_period',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), server_default='DRAFT', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'CONFIRMED')", name=op.f('ck_billing_period_status')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_billing_period_range_order')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['app_user.id'], name=op.f('fk_billing_period_confirmed_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_period')),
    sa.UniqueConstraint('start_date', 'end_date', name='uq_billing_period_range')
    )
    op.create_index(op.f('ix_billing_period_status'), 'billing_period', ['status'], unique=False)
    op.create_table('site',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_site_client_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site')),
    sa.UniqueConstraint('name', name=op.f('uq_site_name'))
    )
    op.create_index(op.f('ix_site_client_id'), 'site', ['client_id'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_no', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('site_id', sa.BigInteger(), nullable=False),
    sa.Column('sales_rep_id', sa.BigInteger(), nullable=True),
    sa.Column('office_id', sa.BigInteger(), nullable=True),
    sa.Column('skip_statement', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_contract_customer_id')),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], name=op.f('fk_contract_office_id')),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_rep.id'], name=op.f('fk_contract_sales_rep_id')),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_contract_site_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract')),
    sa.UniqueConstraint('contract_no', name=op.f('uq_contract_contract_no'))
    )
    op.create_index(op.f('ix_contract_customer_id'), 'contract', ['customer_id'], unique=False)
    op.create_index(op.f('ix_contract_site_id'), 'contract', ['site_id'], unique=False)
    op.create_index(op.f('ix_contract_skip_statement'), 'contract', ['skip_statement'], unique=False)
    op.create_table('import_batch',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('imported_by', sa.BigInteger(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_by'], ['app_user.id'], name=op.f('fk_import_batch_imported_by')),
    sa.ForeignKeyConstraint(['period_id'], ['billing_period.id'], name=op.f('fk_import_batch_period_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batch'))
    )
    op.create_index(op.f('ix_import_batch_period_id'), 'import_batch', ['period_id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('tax_category', sa.Text(), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('total_ex_tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Text(), server_default='DRAFT', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.BigInteger(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'ISSUED', 'SENT', 'PAID')", name=op.f('ck_invoice_status')),
    sa.CheckConstraint("tax_category IN ('STANDARD', 'REDUCED')", name=op.f('ck_invoice_tax_category')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_invoice_revision_positive')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['app_user.id'], name=op.f('fk_invoice_confirmed_by')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_invoice_customer_id')),
    sa.ForeignKeyConstraint(['period_id'], ['billing_period.id'], name=op.f('fk_invoice_period_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice')),
    sa.UniqueConstraint('period_id', 'customer_id', 'tax_category', name='uq_invoice_period_tax')
    )
    op.create_index(op.f('ix_invoice_period_id'), 'invoice', ['period_id'], unique=False)
    op.create_table('period_unlock_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('from_revision', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('unlocked_by', sa.BigInteger(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['billing_period.id'], name=op.f('fk_period_unlock_log_period_id')),
    sa.ForeignKeyConstraint(['unlocked_by'], ['app_user.id'], name=op.f('fk_period_unlock_log_unlocked_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_period_unlock_log'))
    )
    op.create_index(op.f('ix_period_unlock_log_period_id'), 'period_unlock_log', ['period_id'], unique=False)
    op.create_table('invoice_statement',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('billing_group', sa.Text(), nullable=False),
    sa.Column('total_ex_tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("billing_group IN ('EQUIPMENT', 'COUNTER')", name=op.f('ck_invoice_statement_billing_group')),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_invoice_statement_contract_id')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_invoice_statement_invoice_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_statement')),
    sa.UniqueConstraint('invoice_id', 'contract_id', 'billing_group', name='uq_invoice_statement_key')
    )
    op.create_index(op.f('ix_invoice_statement_contract_id'), 'invoice_statement', ['contract_id'], unique=False)
    op.create_index(op.f('ix_invoice_statement_invoice_id'), 'invoice_statement', ['invoice_id'], unique=False)
    op.create_table('issued_document',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=True),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('issued_by', sa.BigInteger(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type IN ('INVOICE', 'STATEMENT', 'BUNDLE_ZIP')", name=op.f('ck_issued_document_doc_type')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_issued_document_invoice_id')),
    sa.ForeignKeyConstraint(['issued_by'], ['app_user.id'], name=op.f('fk_issued_document_issued_by')),
    sa.ForeignKeyConstraint(['period_id'], ['billing_period.id'], name=op.f('fk_issued_document_period_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issued_document'))
    )
    op.create_index(op.f('ix_issued_document_period_id'), 'issued_document', ['period_id'], unique=False)
    op.create_table('rental_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('order_no', sa.Text(), nullable=False),
    sa.Column('po_number_1', sa.Text(), nullable=True),
    sa.Column('po_number_2', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], name=op.f('fk_rental_order_contract_id')),
    sa.ForeignKeyConstraint(['period_id'], ['billing_period.id'], name=op.f('fk_rental_order_period_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rental_order')),
    sa.UniqueConstraint('period_id', 'order_no', name='uq_rental_order_period_no')
    )
    op.create_index(op.f('ix_rental_order_contract_id'), 'rental_order', ['contract_id'], unique=False)
    op.create_index(op.f('ix_rental_order_period_id'), 'rental_order', ['period_id'], unique=False)
    op.create_table('billing_line',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('statement_id', sa.BigInteger(), nullable=True),
    sa.Column('item_name_snapshot', sa.Text(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('shipped_date', sa.Date(), nullable=True),
    sa.Column('rental_start', sa.Date(), nullable=True),
    sa.Column('rental_end', sa.Date(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('base_charge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('duration', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_price_type', sa.Text(), server_default='DAILY', nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), sa.Computed('COALESCE(base_charge, 0) * quantity + COALESCE(unit_price, 0) * COALESCE(duration, 1) * quantity', persisted=True), nullable=False),
    sa.Column('src_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('src_base_charge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('src_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('src_duration', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_billable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_provisional', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('source_key', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("unit_price_type IN ('MONTHLY', 'DAILY', 'SALE')", name=op.f('ck_billing_line_unit_price_type')),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name=op.f('fk_billing_line_item_id')),
    sa.ForeignKeyConstraint(['order_id'], ['rental_order.id'], name=op.f('fk_billing_line_order_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['billing_period.id'], name=op.f('fk_billing_line_period_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statement_id'], ['invoice_statement.id'], name=op.f('fk_billing_line_statement_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_line'))
    )
    op.create_index(op.f('ix_billing_line_is_billable'), 'billing_line', ['is_billable'], unique=False)
    op.create_index(op.f('ix_billing_line_item_id'), 'billing_line', ['item_id'], unique=False)
    op.create_index(op.f('ix_billing_line_order_id'), 'billing_line', ['order_id'], unique=False)
    op.create_index('ix_billing_line_period_active', 'billing_line', ['period_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_billing_line_source_key'), 'billing_line', ['source_key'], unique=False)
    op.create_index(op.f('ix_billing_line_statement_id'), 'billing_line', ['statement_id'], unique=False)
    op.create_table('line_edit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('line_id', sa.BigInteger(), nullable=False),
    sa.Column('field', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('new_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('edited_by', sa.BigInteger(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edited_by'], ['app_user.id'], name=op.f('fk_line_edit_log_edited_by')),
    sa.ForeignKeyConstraint(['line_id'], ['billing_line.id'], name=op.f('fk_line_edit_log_line_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_edit_log'))
    )
    op.create_index('ix_line_edit_log_line_time', 'line_edit_log', ['line_id', 'edited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_line_edit_log_line_time', table_name='line_edit_log')
    op.drop_table('line_edit_log')
    op.drop_index(op.f('ix_billing_line_statement_id'), table_name='billing_line')
    op.drop_index(op.f('ix_billing_line_source_key'), table_name='billing_line')
    op.drop_index('ix_billing_line_period_active', table_name='billing_line', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_billing_line_order_id'), table_name='billing_line')
    op.drop_index(op.f('ix_billing_line_item_id'), table_name='billing_line')
    op.drop_index(op.f('ix_billing_line_is_billable'), table_name='billing_line')
    op.drop_table('billing_line')
    op.drop_index(op.f('ix_rental_order_period_id'), table_name='rental_order')
    op.drop_index(op.f('ix_rental_order_contract_id'), table_name='rental_order')
    op.drop_table('rental_order')
    op.drop_index(op.f('ix_issued_document_period_id'), table_name='issued_document')
    op.drop_table('issued_document')
    op.drop_index(op.f('ix_invoice_statement_invoice_id'), table_name='invoice_statement')
    op.drop_index(op.f('ix_invoice_statement_contract_id'), table_name='invoice_statement')
    op.drop_table('invoice_statement')
    op.drop_index(op.f('ix_period_unlock_log_period_id'), table_name='period_unlock_log')
    op.drop_table('period_unlock_log')
    op.drop_index(op.f('ix_invoice_period_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_import_batch_period_id'), table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_contract_skip_statement'), table_name='contract')
    op.drop_index(op.f('ix_contract_site_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_customer_id'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_site_client_id'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_billing_period_status'), table_name='billing_period')
    op.drop_table('billing_period')
    op.drop_table('sales_rep')
    op.drop_table('office')
    op.drop_index(op.f('ix_item_tax_category'), table_name='item')
    op.drop_index(op.f('ix_item_billing_group'), table_name='item')
    op.drop_table('item')
    op.drop_table('customer')
    op.drop_index(op.f('ix_client_normalized_name'), table_name='client')
    op.drop_table('client')
    op.drop_table('app_user')
    # ### end Alembic commands ###
