"""issued_documentのinvoice_idにON DELETE SET NULLを追加

Revision ID: f02814fc20eb
Revises: edd85523cefa
Create Date: 2026-08-19 20:47:33.143422
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f02814fc20eb'
down_revision: str | None = 'edd85523cefa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_issued_document_invoice_id'), 'issued_document', type_='foreignkey')
    op.create_foreign_key(op.f('fk_issued_document_invoice_id'), 'issued_document', 'invoice', ['invoice_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_issued_document_invoice_id'), 'issued_document', type_='foreignkey')
    op.create_foreign_key(op.f('fk_issued_document_invoice_id'), 'issued_document', 'invoice', ['invoice_id'], ['id'])
    # ### end Alembic commands ###
